sudo: required
language: cpp
dist: trusty
matrix:
  include:
    - os: osx
      osx_image: xcode10
    - os: linux
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libboost-filesystem1.55-dev
            - libboost-test1.55-dev
            - libboost-program-options1.55-dev
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90; fi
before_script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sed -i -e 's/test\/TestSystem.cxx//g' CMakeLists.txt; fi
  - mkdir build; cd build
script:
  - cmake ..
  - make -j
  - make test
notifications:
  email: false
