language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env: TOOL=test
    - os: linux
      dist: xenial
      env: TOOL=test
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libboost-system1.58-dev
            - libboost-filesystem1.58-dev
            - libboost-test1.58-dev
            - libboost-program-options1.58-dev
    - os: linux
      dist: xenial
      env: TOOL=clang-format
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-format-7
      compiler: clang
      branches:
        only:
          - dev
before_script: 
  - if [[ $TOOL == "test" ]]; then sed -i -e 's/test\/TestSystem.cxx//g' CMakeLists.txt; fi
  - if [[ $TOOL == "test" ]]; then mkdir build; cd build; fi
script:
  - if [[ $TOOL == "test" ]]; cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8; fi
  - if [[ $TOOL == "test" ]]; make -j; fi
  - if [[ $TOOL == "test" ]]; make test; fi
  - if [[ $TOOL == "clang-format" ]] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      cd $TRAVIS_BUILD_DIR;
      BASE_COMMIT=$(git rev-parse $TRAVIS_BRANCH);
      COMMIT_FILES=$(git diff --name-only $BASE_COMMIT | grep -i -v LinkDef);
      RESULT_OUTPUT="$(git-clang-format-7 --commit $BASE_COMMIT --diff --binary `which clang-format-7` $COMMIT_FILES)";
      if [ "$RESULT_OUTPUT" == "no modified files to format" ] || [ "$RESULT_OUTPUT" == "clang-format did not modify any files" ] ; then
        exit 0;
      else
        echo "$RESULT_OUTPUT";
        exit 1;
      fi
    fi
notifications:
  email: false
